"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download } from "lucide-react";
import { ScrollArea } from "@/components/ui/scroll-area";

const sampleCRS = {
  project_title: "E-Commerce Mobile Application",
  description:
    "A modern mobile application for online shopping with integrated payment processing, inventory management, and customer relationship features.",
  functional_requirements: [
    {
      id: "FR-001",
      priority: "High",
      description: "User registration and authentication with email and social login options",
    },
    {
      id: "FR-002",
      priority: "High",
      description: "Product catalog with search, filter, and category browsing capabilities",
    },
    {
      id: "FR-003",
      priority: "High",
      description: "Shopping cart functionality with add, remove, and quantity adjustment",
    },
    {
      id: "FR-004",
      priority: "Medium",
      description: "Secure payment processing supporting credit cards and digital wallets",
    },
    {
      id: "FR-005",
      priority: "Medium",
      description: "Order tracking and history for customers",
    },
  ],
  non_functional_requirements: {
    performance: "App should load within 2 seconds on 4G networks",
    security: "PCI DSS compliance for payment processing, encrypted data transmission",
    scalability: "Support 10,000 concurrent users with 99.9% uptime",
  },
  stakeholders: ["Product Owner", "Development Team", "End Users (Shoppers)", "Payment Gateway Provider"],
  target_users: "Online shoppers aged 18-45, primarily mobile-first consumers",
  constraints: {
    budget: "$150,000",
    timeline: "6 months for MVP launch",
    technical: "Must integrate with existing inventory management system",
  },
  success_metrics: ["100,000 app downloads in first 3 months", "Average session duration > 5 minutes", "Conversion rate > 3%"],
};

export function SampleCRSModal() {
  const [open, setOpen] = useState(false);

  const handleExport = () => {
    // Placeholder for export functionality
    alert("Sample CRS export feature - would download PDF here");
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="gap-2 hover:bg-muted transition-all duration-300 hover:scale-105">
          <FileText className="h-4 w-4" />
          View Sample CRS
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-4xl max-h-[90vh]">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            <span>Sample CRS Document</span>
            <Button size="sm" variant="outline" className="gap-2 hover:bg-muted transition-all duration-300" onClick={handleExport}>
              <Download className="h-4 w-4" />
              Export PDF
            </Button>
          </DialogTitle>
          <DialogDescription>
            Example of a complete Customer Requirements Specification generated by BridgeAI
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[70vh] pr-4">
          <div className="space-y-6">
            {/* Project Title */}
            <div>
              <h3 className="text-lg font-semibold mb-2">Project Title</h3>
              <p className="text-muted-foreground">{sampleCRS.project_title}</p>
            </div>

            {/* Description */}
            <div>
              <h3 className="text-lg font-semibold mb-2">Description</h3>
              <p className="text-muted-foreground">{sampleCRS.description}</p>
            </div>

            {/* Functional Requirements */}
            <div>
              <h3 className="text-lg font-semibold mb-3">Functional Requirements</h3>
              <div className="space-y-3">
                {sampleCRS.functional_requirements.map((req, index) => (
                  <div key={index} className="border rounded-lg p-4">
                    <div className="flex items-center gap-2 mb-2">
                      <Badge variant="outline">{req.id}</Badge>
                      <Badge
                        variant={req.priority === "High" ? "default" : "secondary"}
                      >
                        {req.priority}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground">{req.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Non-Functional Requirements */}
            <div>
              <h3 className="text-lg font-semibold mb-3">Non-Functional Requirements</h3>
              <div className="space-y-3">
                <div>
                  <h4 className="font-medium text-sm mb-1">Performance</h4>
                  <p className="text-sm text-muted-foreground">{sampleCRS.non_functional_requirements.performance}</p>
                </div>
                <div>
                  <h4 className="font-medium text-sm mb-1">Security</h4>
                  <p className="text-sm text-muted-foreground">{sampleCRS.non_functional_requirements.security}</p>
                </div>
                <div>
                  <h4 className="font-medium text-sm mb-1">Scalability</h4>
                  <p className="text-sm text-muted-foreground">{sampleCRS.non_functional_requirements.scalability}</p>
                </div>
              </div>
            </div>

            {/* Stakeholders */}
            <div>
              <h3 className="text-lg font-semibold mb-2">Stakeholders</h3>
              <div className="flex flex-wrap gap-2">
                {sampleCRS.stakeholders.map((stakeholder, index) => (
                  <Badge key={index} variant="secondary">
                    {stakeholder}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Target Users */}
            <div>
              <h3 className="text-lg font-semibold mb-2">Target Users</h3>
              <p className="text-muted-foreground">{sampleCRS.target_users}</p>
            </div>

            {/* Constraints */}
            <div>
              <h3 className="text-lg font-semibold mb-3">Constraints</h3>
              <div className="space-y-2">
                <p className="text-sm"><span className="font-medium">Budget:</span> {sampleCRS.constraints.budget}</p>
                <p className="text-sm"><span className="font-medium">Timeline:</span> {sampleCRS.constraints.timeline}</p>
                <p className="text-sm"><span className="font-medium">Technical:</span> {sampleCRS.constraints.technical}</p>
              </div>
            </div>

            {/* Success Metrics */}
            <div>
              <h3 className="text-lg font-semibold mb-2">Success Metrics</h3>
              <ul className="list-disc list-inside space-y-1">
                {sampleCRS.success_metrics.map((metric, index) => (
                  <li key={index} className="text-sm text-muted-foreground">{metric}</li>
                ))}
              </ul>
            </div>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
